baseURL = 'https://berryphillips.com/'
languageCode = 'en-gb'
title = 'Berry Phillips'

[params]
centerTheme = true

# theme = "re-terminal"

[languages]
[languages.en.params]
title = "Berry Phillips"

[languages.en.params.logo]
logoText = "Berry Phillips"

[module]
[[module.imports]]
path = 'github.com/mirus-ua/hugo-theme-re-terminal'
